name: Android CI

on:
  push:
    branches: 
      - main
    tags:
      - "v[0-9].[0-9].[0-9]"

env:
  KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Checkout keystore repo
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
        token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
        path: app/keystore
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
         ./gradlew assembleRelease  --stacktrace --info
         ./gradlew bundleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
         name: build
         path: app/build/outputs/apk/release/app-release.apk
         
  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download APK from build
      uses: actions/download-artifact@v3
      with:
        name: build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: ${{ github.event.repository.name }} v${{ github.run_number }}
    - name: Upload Release APK
      id: upload_release_asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: apk/app-debug.apk
        asset_name: ${{ github.event.repository.name }}.apk
        asset_content_type: application/vnd.android.package-archive
